### PR TITLE
Reg 3/boilerplate

### PR DESCRIPTION
**Pull request by yunhsincynthiachen**
Jira: https://olinjs.atlassian.net/browse/REG-3

### CODE REVIEW

**Comment by yunhsincynthiachen** [comment]
Needs redux boilerplate

**Comment by billmwong** [comment]
@yunhsincynthiachen should we gitignore the bundle.js?

**Comment by yunhsincynthiachen** [comment]
@billmwong no, because if this were pushed to heroku, i don't think heroku would build all jsx into a bundle.js

**Comment by billmwong** [comment]
@yunhsincynthiachen hmmm but it seems like every time someone changes something webpack will update bundle.js? And then won't we get nasty merge conflicts there

**Comment by yunhsincynthiachen** [comment]
@billmwong i guess if we're not shipping the code into development and in regards to version control, it makes sense to gitignore bundle.js. if i remove bundle.js though, the scripts folder is empty and won't show up on github

**Comment by yunhsincynthiachen** [comment]
@billmwong Never mind! Webpack will create a new scripts folder with a bundle.js!!

**Comment by billmwong** [comment]
Oh nice! We can address heroku when we get there.

**Comment by yunhsincynthiachen** [comment]
:+1:

**Review by billmwong — APPROVED** [review]

**Pull request merged**
