### PR TITLE
ADD: sass and css modules to the webpack config

### PR DESCRIPTION
**Pull request by jagreene**
Jira: https://olinjs.atlassian.net/browse/REG-14

### CODE REVIEW

**Review by yunhsincynthiachen — COMMENTED** [review]
Looks good to me! Do we want to have an example css or sass file? I feel like it might be good. At the same time, I really like the css-modules article you put up in having people learn it by themselves. Lmk what you think

**Comment by billmwong** [comment]
I think those resources should go somewhere else, like the chat or in the olinjs repo, instead of in the code.

**Comment by jagreene** [comment]
Maybe we should make a wiki where students can start aggregating information about the stack we are using?
I think having one or two resources inline makes groking weird code easier and something I've found really helpful when other people do it.

**Comment by yunhsincynthiachen** [comment]
I like the wiki idea, and I'm okay with having some inline resources for direct referencing.

**Comment by billmwong** [comment]
Yeah the wiki is a good idea! I can make a jira ticket to kick off the wiki.

**Review by billmwong — APPROVED** [review]
Good to go from me!

**Review by yunhsincynthiachen — APPROVED** [review]
Same!

**Pull request merged**
