### PR TITLE
Reg 46/add course dropdown

### PR DESCRIPTION
**Pull request by Halliax**
https://olinjs.atlassian.net/browse/REG-46

### CODE REVIEW

**Review by arianaolson419 — APPROVED** [review]

**Review by billmwong — CHANGES_REQUESTED** [review]
Code looks good, but can I get a screenshot?

**Comment by Halliax** [comment]
whoops, didn't see this til now
course_dropdown

**Review by billmwong — APPROVED** [review]
Nice!

**Comment by billmwong** [comment]
@Halliax Resolve conflicts please

**Comment by billmwong** [comment]
Waiting to test new code before merging

**Comment by billmwong** [comment]
:white_check_mark: tested!

**Pull request merged**
