### PR TITLE
REG-18 Make linter run in backend automatically

### PR DESCRIPTION
**Pull request by billmwong**
Jira: https://olinjs.atlassian.net/browse/REG-18

### CODE REVIEW

**Review by yunhsincynthiachen — COMMENTED** [review]
The lint is detecting a ton of problems with the current boilerplate. Should it all be changed, or leave it for people to change while they are using lint?

**Comment by billmwong** [comment]
@yunhsincynthiachen Uhh because webpack only touches the frontend? I don't know if I can set that up for the backend code, because I saw this comment: https://github.com/olin/register/blob/master/webpack.config.js#L33

**Comment by yunhsincynthiachen** [comment]
@billmwong Yup! I had realized that and changed my comment. What about the errors that it's detecting right now. Are we going to change that, or should we just have students make those changes on their own?

**Comment by billmwong** [comment]
@yunhsincynthiachen Yeah I'm fixing all of them now

**Review by yunhsincynthiachen — APPROVED** [review]
Perfect!

**Pull request merged**
