### PR TITLE
Reg 38/update current style

### PR DESCRIPTION
**Pull request by Halliax**
https://olinjs.atlassian.net/browse/REG-38

### CODE REVIEW

**Comment by Halliax** [comment]
homepage-regular

**Comment by Halliax** [comment]
homepage-small

**Comment by Halliax** [comment]
settings-page

**Review by robbie-sundstrom — APPROVED** [review]

**Review by BrennaManning — APPROVED** [review]
This looks good!

**Review by billmwong — APPROVED** [review]

**Pull request merged**
